<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>rover_navigation</name>
  <version>1.0.0</version>
  <description>This ROS2 package contains all the Nav2 functionality of the project, including launch files.</description>
  <maintainer email="moodyellam@gmail.com">Ella Moody</maintainer>
  <author email="moodyellam@gmail.com">Ella Moody</author>
  <license>Apache License 2.0</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <build_depend>rclcpp</build_depend>
  <build_depend>pluginlib</build_depend>

  <exec_depend>nav2_core</exec_depend>
  <exec_depend>nav2_util</exec_depend>
  <exec_depend>rclcpp</exec_depend>

  <export>
    <build_type>ament_cmake</build_type>
    <!-- Will need to export the plugin for hardware and tasks execution here -->
  </export>
</package>
