services:
  rosdev:
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

  docker_zed:
    image: stereolabs/zed:4.2-py-runtime-jetson-jp6.0.0
    container_name: rerassor_zed
    network_mode: host
    entrypoint: "/bin/sh"