services:
  cislune-re-rassor:
    build:
      context: ../
      dockerfile: docker/Dockerfile
    container_name: cislune-re-rassor
    network_mode: host
    privileged: true
    environment:
      - DISPLAY=${DISPLAY}
      - ROS_DOMAIN_ID=1
      - QT_X11_NO_MITSHM=1
    volumes:
      - ../src:/workspace/src
      - ../build:/workspace/build
      - ../install:/workspace/install
      - ../log:/workspace/log
      - /tmp/.X11-unix:/tmp/.X11-unix  # GUI apps (RViz, Gazebo)
      - /dev:/dev  # Teensy or serial devices
    devices:
      - /dev/dri  # GPU for Gazebo rendering
    command: bash
