controller_manager:
  ros__parameters:
    update_rate: 50        # controller update frequency in Hz
    # (use_sim_time: false will be set in launch for hardware, true for sim)

#TODO: UPDATE THIS WITH THE ACTUAL MEASUREMENTS
diff_drive_controller:
  ros__parameters:
    type: diff_drive_controller/DiffDriveController
    left_wheel_names: ["front_left_wheel_joint", "back_left_wheel_joint"]
    right_wheel_names: ["front_right_wheel_joint", "back_right_wheel_joint"]
    wheel_separation: 0.50            # distance between left and right wheels (m)
    wheel_radius: 0.15               # radius of the wheels (m)
    use_stamped_vel: false           # using Twist messages (not stamped) for cmd_vel
    base_frame_id: base_link
    odom_frame_id: odom
    enable_odom_tf: true             # publish odom->base_link tf
    publish_rate: 50.0               # odometry publication rate
    cmd_vel_timeout: 0.5             # timeout to stop if no cmd received
    # velocity and acceleration limits (optional):
    linear.x.max_velocity: 1.0       # m/s
    linear.x.max_acceleration: 1.0   # m/s^2
    angular.z.max_velocity: 1.0      # rad/s
    angular.z.max_acceleration: 1.0  # rad/s^2

joint_state_broadcaster:
  ros__parameters:
    type: joint_state_broadcaster/JointStateBroadcaster
