controller_manager:
  ros__parameters:
    update_rate: 30  # Hz

    diff_cont:
      type: diff_drive_controller/DiffDriveController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

diff_cont:
  ros__parameters:
    left_wheel_names: [ "front_left_wheel_joint", "rear_left_wheel_joint" ]
    right_wheel_names: [ "front_right_wheel_joint", "rear_right_wheel_joint" ]

    left_wheel_reverse: true

    # Separation between a left and right wheels in meters
    wheel_separation: 0.60062
    wheel_radius: 0.115

    publish_rate: 30.0
    odom_frame_id: odom
    base_frame_id: base_link

    open_loop: true
    enable_odom_tf: true

    cmd_vel_timeout: 0.5
    use_stamped_vel: true

    # Publish limited velocity
    publish_cmd: true

    # Publish wheel data
    publish_wheel_data: true